CREATE OR REPLACE TABLE `{{ params.project_id }}.{{ params.dataset.cl }}.rb_sku_line_rebate` 
  AS (
    SELECT lr.global_entity_id,
      lr.country_code,
      lr.country,
      lr.global_supplier_id,
      lr.sku,
      lr.supplier_name,
      lr.finance_system_id,
      lr.sup_id,
      lr.unit_of_measure,
      lr.trading_term_name,
      lr.trading_term_type,
      lr.rebate_term_value,
      lr.term_value_type,
      lr.term_start_date,
      lr.term_applicability,
      lr.term_frequency,
      lr.term_end_date,
      lr.month,
      lr.rebate_currency,
      lr.contract_id,
      lr.opp_id,
      lr.account_id,
      lr.account_owner,
      lr.contract_startdate,
      lr.contract_enddate,
      lr.contract_effective_enddate,
      lr.contract_status,
      lr.contract_term_type,
      lr.contract_term_id,
      lr.opp_term_id,
      lr.term_pim_brand_id,
      lr.sku_brand_name,
      lr.sku_categ_level_one,
      lr.sku_categ_level_two,
      lr.sku_level_three,
      lr.sku_level_four,
      lr.sku_level_five,
      lr.sku_level_six,
      lr.barcodes,
      sa.received_local_month,
      sa.delivered_net_amount,
      sa.returned_net_amount,
      sa.delivered_gross_amount,
      sa.returned_gross_amount,
      sa.sup_net_purchase,
      sa.sup_net_return,
      sa.sup_gross_purchase,
      sa.sup_gross_return,
      lr.sup_valid_gross_purchase,
      lr.sup_valid_gross_return,
      lr.sup_valid_net_purchase,
      lr.sup_valid_net_return,
      lr.sup_term_valid_gross_purchase,
      lr.sup_term_valid_gross_return,
      lr.sup_term_valid_net_purchase,
      lr.sup_term_valid_net_return,
      lr.term_comments,
      lr.excise_tax,
      lr.fixed_vat,
      lr.fixed_vat_percentage,
      STRING_AGG(DISTINCT lr.po_id ORDER BY lr.po_id) AS poid_list,
      SUM(lr.rebate) AS total_rebate,
      FROM `{{ params.project_id }}.{{ params.dataset.cl }}.rb_line_rebate` AS lr
      LEFT JOIN (
        SELECT sa.sup_id,
          sa.sku,
          sa.country_code,
          sa.received_local_month,
          sa.delivered_net_amount,
          sa.returned_net_amount,
          sa.delivered_gross_amount,
          sa.returned_gross_amount,
          SUM(sa.delivered_net_amount) OVER (PARTITION BY sa.sup_id) AS sup_net_purchase,
          SUM(sa.returned_net_amount) OVER (PARTITION BY sa.sup_id) AS sup_net_return,
          SUM(sa.delivered_gross_amount) OVER (PARTITION BY sa.sup_id) AS sup_gross_purchase,
          SUM(sa.returned_gross_amount) OVER (PARTITION BY sa.sup_id) AS sup_gross_return,
          FROM `{{ params.project_id }}.{{ params.dataset.cl }}.rb_monthly_sku_amount`  AS sa
        WHERE TRUE
        GROUP BY ALL
      ) AS sa ON sa.sku = lr.sku
      AND sa.sup_id = lr.sup_id
      AND sa.country_code = lr.country_code
      AND DATE_TRUNC(sa.received_local_month, month) = lr.month
    GROUP BY ALL
  );
